# Generated by Django 3.0.4 on 2020-03-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotes1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author1name', models.CharField(max_length=50)),
                ('quote', models.TextField()),
            ],
        ),
    ]
