# Generated by Django 3.0.4 on 2020-03-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_quotes1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quotes1',
        ),
    ]
